version: '3.8'

services:
  magnete:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
      # - "5173:5173"
    networks:
      - magnete

#   uptime-kuma:
#     image: louislam/uptime-kuma:1
#     volumes:
#       - ./uptime-kuma/data:/app/data
#       - /run:/run
#     networks:
#       - magnete
#     restart: unless-stopped

  nginx:
    image: mirror.gcr.io/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
      - /etc/certbot/www:/var/www/certbot/:ro
      - /etc/certbot/conf:/etc/letsencrypt/:ro
    restart: always
    networks:
      - magnete

  certbot:
    image: mirror.gcr.io/certbot/certbot:latest
    volumes:
      - /etc/nginx/certbot/www:/var/www/certbot/:rw
      - /etc/nginx/certbot/conf:/etc/letsencrypt/:rw

# networks:
#   magnete: