name: Deploy app via Docker-compose

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Docker Image Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Тестовая сборка Docker-образа
      - name: Docker build test
        run: docker build -t your-app:test .
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          tar -cvf magnete.tar ../Magnete/

      - name: Copy files to remote server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "magnete.tar"
          target: "/root/"

      - name: Execute Docker Compose via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            tar -xvf magnete.tar
            cd ~/Magnete
            docker-compose pull
            docker-compose down
            docker-compose build
            docker-compose up -d --remove-orphans

  # update-cert:
  #   name: update-certificate
  #   runs-on: ubuntu-latest

  #   steps:

  #     - uses: actions/checkout@v2

  #     - name: Execute Docker Compose via SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd ~/Magnete
  #           docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d magnete-shop.com -d www.magnete-shop.com