name: Deploy app via Docker-compose

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Docker Image Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Тестовая сборка Docker-образа
      - name: Docker build test
        run: docker build -t your-app:test .
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

      # - name: Set up Docker Compose
      #   run: docker-compose version
      - name: Очистить старые файлы на сервере через SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/Magnete/*
            mkdir -p ~/Magnete

      - name: Copy files to remote server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/Magnete"

      - name: Execute Docker Compose via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Magnete
            docker-compose pull
            docker-compose down
            docker-compose build
            docker-compose up -d --remove-orphans